name: K9s Test

on:
  workflow_dispatch:
    push:
    branches:
      - master
    tags:
      - rc*
      - v*
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest-large
    steps:
      - name: Checkout Code
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29  # v4.1.6

      - name: Install Go
        uses: actions/setup-go@cdcb36043654635271a94b9a6d1392de5bb323a7  # v5.0.1
        with:
          go-version-file: go.mod
          cache-dependency-path: go.sum

      - name: Setup GO env
        run: go env -w CGO_ENABLED=0

      - name: Run Tests
        run: make test
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
